pipeline {
    agent any
    tools {
        maven 'MAVEN'
    }
    parameters {
        choice(
            name: 'BRANCH', 
            choices: ['master', 'testng'], 
            description: 'Selecciona la rama que deseas compilar'
        )
    }
    stages {
        stage('Verificar y Clonar Repositorio') {
            steps {
                script {
                    def projectDir = 'simple-java-maven-app'
                    if (fileExists(projectDir)) {
                        echo "El proyecto ya existe. Eliminando carpeta..."
                        deleteDir()
                    }
                    echo "Clonando repositorio desde GitHub, rama: ${params.BRANCH}..."
                    git branch: params.BRANCH, url: 'https://github.com/Danielms111/simple-java-maven-app.git'
                }
            }
        }
        stage('Ejecutar Pruebas Unitarias') {
            steps {
                echo 'Ejecutando pruebas unitarias con Maven...'
                script {
                    try {
                        sh 'mvn test'
                    } catch (Exception e) {
                        echo 'Las pruebas unitarias fallaron.'
                        currentBuild.result = 'FAILURE'
                        throw e
                    }
                }
            }
        }
    }
    post {
        success {
            echo 'Pipeline ejecutado con éxito. Las pruebas pasaron.'
        }
        failure {
            echo 'El pipeline falló. Las pruebas no pasaron.'
        }
    }
}

